theme: jekyll-theme-minimal
title: Unknownstone Place
description: "Unknownstone's Place of things, anything."
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
